# configuration for the basic sweeper that is normally used by hydra

# change the log/output dir
hydra:
  sweep:
    # format of timestamp is Year-Month-Day so the folders are ordered correctly
    dir: ./logs/${hydra.job.config_name}/sweep-${now:%Y-%m-%d_%H-%M-%S}
