# @package _global_
# config for an experiment with pretraining + fine-tuning, only the classifier is trained during fine-tuning

defaults:
  - fpt_config@_global_
  - ../sweeper/basic_sweep_config@_global_
  - ../launcher/joblib_config@_global_
  - _self_

# don't need to overwrite anything here, since this is the basic config for the experiment
